# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfb43d65cb67096821adf1f58d7dd7614744861d76cb7bb8baa5623c9a049126590c3c270764dd1c68a4c4e75838189f5d4562a2b7adde8dcf5b4623f17fd594

test:
  secret_key_base: 9dafd3a4539586d1f9036854154f4ecdced5681bee7ac08cee2c5a30deb6d513cc4118026de1e9f41b94b1e2348058a2964aaa5136392fda28abfb7b152687e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
